spring:
  profiles:
    active: dev

  elasticsearch:
    uris: http://localhost:9200

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      file-size-threshold: 2KB
      location: ${file.upload.temp-dir}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://192.168.125.128:3306/full_text_searching?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # MyBatis-Plus配置
  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: auto
        table-prefix: t_
    mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG

dify:
  base-url: http://localhost:18080
  api-key: dataset-agCdYnX6Yj0MYf9DUMqOWMMW
  sync-enabled: true

# 文件上传配置
file:
  upload:
    permanent-dir: ./file/upload  # 永久存储路径